<?php
/**
 * Interaction row.
 *
 * @package RagInteractionLoggerMonitor
 */

namespace RILM\Repository;

use DateTimeImmutable;
use DateTimeZone;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * One row of the interactions table, with PHP types and `NULL` preserved.
 *
 * A column that was not selected (for example the full texts in the list) reads
 * as `NULL`: `NULL` and "empty string" stay different values.
 */
class Interaction {

	/**
	 * Row id.
	 *
	 * @var int
	 */
	public $id = 0;

	/**
	 * Timestamp as stored (UTC, `Y-m-d H:i:s.v`).
	 *
	 * @var string
	 */
	public $ts = '';

	/**
	 * Duration of the turn in milliseconds.
	 *
	 * @var int|null
	 */
	public $duration_ms;

	/**
	 * Instance name.
	 *
	 * @var string
	 */
	public $instance = '';

	/**
	 * User identifier (may be personal data).
	 *
	 * @var string
	 */
	public $user_id = '';

	/**
	 * Turn identifier.
	 *
	 * @var string|null
	 */
	public $turn_id;

	/**
	 * Outcome: generated, fast_reply or incomplete.
	 *
	 * @var string
	 */
	public $outcome = '';

	/**
	 * Question (may be personal data).
	 *
	 * @var string|null
	 */
	public $question;

	/**
	 * Answer generated by the model (may be personal data).
	 *
	 * @var string|null
	 */
	public $llm_answer;

	/**
	 * Answer delivered to the user (may be personal data).
	 *
	 * @var string|null
	 */
	public $delivered;

	/**
	 * Whether Guardrails ran.
	 *
	 * @var bool
	 */
	public $guard_present = false;

	/**
	 * Input verdict; `NULL` means no block recorded.
	 *
	 * @var string|null
	 */
	public $input_verdict;

	/**
	 * Output verdict; `NULL` means no block recorded.
	 *
	 * @var string|null
	 */
	public $output_verdict;

	/**
	 * Whether another plugin replied; `NULL` means not recorded.
	 *
	 * @var bool|null
	 */
	public $other_plugin_reply;

	/**
	 * Number of recalled sources.
	 *
	 * @var int|null
	 */
	public $recall_count;

	/**
	 * Best recall score.
	 *
	 * @var float|null
	 */
	public $recall_top_score;

	/**
	 * Tools used (column added later, only in the detail).
	 *
	 * @var string|null
	 */
	public $tools_used;

	/**
	 * Tool input (column added later, only in the detail).
	 *
	 * @var string|null
	 */
	public $tool_input;

	/**
	 * Tool output (column added later, only in the detail).
	 *
	 * @var string|null
	 */
	public $tool_output;

	/**
	 * Recall sources (column added later, only in the detail).
	 *
	 * @var string|null
	 */
	public $recall_sources;

	/**
	 * Whether the question was cut to the preview length.
	 *
	 * @var bool
	 */
	public $question_truncated = false;

	/**
	 * Whether the delivered answer was cut to the preview length.
	 *
	 * @var bool
	 */
	public $delivered_truncated = false;

	/**
	 * Builds an interaction from a database row.
	 *
	 * @param array $row            Row keyed by column name, values as returned by the driver.
	 * @param int   $preview_length When above zero, question and delivered are cut to this many characters.
	 * @return self
	 */
	public static function from_row( array $row, int $preview_length = 0 ): self {
		$interaction = new self();

		$interaction->id                 = (int) ( $row['id'] ?? 0 );
		$interaction->ts                 = (string) ( $row['ts'] ?? '' );
		$interaction->duration_ms        = self::nullable_int( $row, 'duration_ms' );
		$interaction->instance           = (string) ( $row['instance'] ?? '' );
		$interaction->user_id            = (string) ( $row['user_id'] ?? '' );
		$interaction->turn_id            = self::nullable_string( $row, 'turn_id' );
		$interaction->outcome            = (string) ( $row['outcome'] ?? '' );
		$interaction->llm_answer         = self::nullable_string( $row, 'llm_answer' );
		$interaction->guard_present      = self::nullable_bool( $row, 'guard_present' ) ?? false;
		$interaction->input_verdict      = self::nullable_string( $row, 'input_verdict' );
		$interaction->output_verdict     = self::nullable_string( $row, 'output_verdict' );
		$interaction->other_plugin_reply = self::nullable_bool( $row, 'other_plugin_reply' );
		$interaction->recall_count       = self::nullable_int( $row, 'recall_count' );
		$interaction->recall_top_score   = self::nullable_float( $row, 'recall_top_score' );
		$interaction->tools_used         = self::nullable_string( $row, 'tools_used' );
		$interaction->tool_input         = self::nullable_string( $row, 'tool_input' );
		$interaction->tool_output        = self::nullable_string( $row, 'tool_output' );
		$interaction->recall_sources     = self::nullable_string( $row, 'recall_sources' );

		list( $interaction->question, $interaction->question_truncated )   = self::preview( self::nullable_string( $row, 'question' ), $preview_length );
		list( $interaction->delivered, $interaction->delivered_truncated ) = self::preview( self::nullable_string( $row, 'delivered' ), $preview_length );

		return $interaction;
	}

	/**
	 * Returns the timestamp as a date in UTC.
	 *
	 * @return DateTimeImmutable
	 */
	public function timestamp(): DateTimeImmutable {
		return new DateTimeImmutable( $this->ts, new DateTimeZone( 'UTC' ) );
	}

	/**
	 * Cuts a text to the preview length.
	 *
	 * @param string|null $text   Text, or null.
	 * @param int         $length Preview length; zero or less means no cut.
	 * @return array{0: string|null, 1: bool} Text and whether it was cut.
	 */
	private static function preview( ?string $text, int $length ): array {
		if ( null === $text || $length <= 0 || mb_strlen( $text ) <= $length ) {
			return array( $text, false );
		}

		return array( mb_substr( $text, 0, $length ), true );
	}

	/**
	 * Reads a nullable string column.
	 *
	 * @param array  $row Row.
	 * @param string $key Column name.
	 * @return string|null
	 */
	private static function nullable_string( array $row, string $key ): ?string {
		return isset( $row[ $key ] ) ? (string) $row[ $key ] : null;
	}

	/**
	 * Reads a nullable integer column.
	 *
	 * @param array  $row Row.
	 * @param string $key Column name.
	 * @return int|null
	 */
	private static function nullable_int( array $row, string $key ): ?int {
		return isset( $row[ $key ] ) ? (int) $row[ $key ] : null;
	}

	/**
	 * Reads a nullable float column.
	 *
	 * @param array  $row Row.
	 * @param string $key Column name.
	 * @return float|null
	 */
	private static function nullable_float( array $row, string $key ): ?float {
		return isset( $row[ $key ] ) ? (float) $row[ $key ] : null;
	}

	/**
	 * Reads a nullable boolean column.
	 *
	 * @param array  $row Row.
	 * @param string $key Column name.
	 * @return bool|null
	 */
	private static function nullable_bool( array $row, string $key ): ?bool {
		return isset( $row[ $key ] ) ? (bool) (int) $row[ $key ] : null;
	}
}
